### ISSUE TITLE
Mechanism to keep orca_backend in synch with Actual Network state.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_ui#31]
Use Case -

1. User makes some changes on device (via cli for example) when the ORCA was down but device was already discovered in ORCA, when the ORCA comes up as device was already discovered in ORCA, a discovery will not be triggered hence the changes will not be visible in ORCA untill user rediscovers the device.
2. User makes some changes on device (via cli for example) when the ORCA was up, but user make config changes for which gNMI subscription notifications are not supported. In this case also ORCA will not be able to get changes done in the config untill user rediscovers the device.

ORCA_UI -

- [x] ORCA_UI should provide the mechanism to schedule a regular full discovery, with
- - [x] a dropdown to rediscover one or more or all the devices from the already discovered device list,
- - [x] Interval - At which discovery should trigger regularly (every 20 mins, 40 mins, 60 mins),
- [x] ORCA_UI - Resync Button on each tab to trigger the discovery of that specific feature for that specific device.
- [x] ORCA_UI  - Any set operation should be blocked during any device discovery or feature discovery. If not done this way, Neo4J might remain in inconsistent state.

**Comment by rahul-1475** [comment]
Backend task has been moved to issue [#72](https://github.com/STORDIS/orca_backend/issues/72)

**Comment by vivek-metricdust** [comment]
Integration test done and found below issue in backend

1. scheduler did not add log in log panel
2. when scheduled discovery is in progress it did not give 400 error 

Had informed @rahul-1475

**Comment by kamalkrbh** [comment]
Functionality needs to be covered by tests.

**Comment by vivek-metricdust** [comment]
> Functionality needs to be covered by tests.

UI test cases added - [orca_ui_test/PR/9](https://github.com/STORDIS/orca_ui_test/pull/9)

**Comment by vivek-metricdust** [comment]
PR updated with [Mechanisam to keep in sync #168](https://github.com/STORDIS/orca_ui/pull/168)

- changing the button label to rediscover in all tabs
-  changing the Sync in to Rediscover in in device info tab
-  removed the select sync time option 
-  fixed the STP issue

**Comment by kamalkrbh** [comment]
Following issue still exists - 
Change the frequency to 10 mins -> apply config -> change to None - > apply config -> Drop down shows 10 mins

**Comment by vivek-metricdust** [comment]
> Following issue still exists - Change the frequency to 10 mins -> apply config -> change to None - > apply config -> Drop down shows 10 mins

fixed in - [9905bd1](https://github.com/STORDIS/orca_ui/pull/168/commits/9905bd14a39f24d5d79a5483346cebfc94ab82c0)
